# Generated by Django 4.2.2 on 2023-07-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Resort_name', models.CharField(max_length=100)),
                ('Resort_price', models.IntegerField()),
                ('Resort_place', models.CharField(max_length=100)),
            ],
        ),
    ]
