# Generated by Django 4.2.2 on 2023-07-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Resort_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Resort_place',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Resort_price',
        ),
    ]
