# Generated by Django 4.2.2 on 2023-07-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_customer_resort_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Resort_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='Resort_place',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='Resort_price',
            field=models.IntegerField(null=True),
        ),
    ]
