# Generated by Django 4.2.2 on 2023-07-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_customer_resort_name_customer_resort_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Adults',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='CheckIn',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='CheckOut',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='Kids',
            field=models.IntegerField(null=True),
        ),
    ]
